// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWgucuXfqfClcu738fXH1zT_GpTKrdhM',
    appId: '1:775850665665:web:1c78adf7f69ab8e8f7d640',
    messagingSenderId: '775850665665',
    projectId: 'ralunorvegia',
    authDomain: 'ralunorvegia.firebaseapp.com',
    storageBucket: 'ralunorvegia.appspot.com',
    measurementId: 'G-5KXERDYQPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVX5jutJ68Frliyw2bC-IA_AndKVcZewg',
    appId: '1:775850665665:android:bd99a46ca9a39f6af7d640',
    messagingSenderId: '775850665665',
    projectId: 'ralunorvegia',
    storageBucket: 'ralunorvegia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Vrear_iITmNGdn9urWC0Zunw9X1RYys',
    appId: '1:775850665665:ios:69dc87772a4394ecf7d640',
    messagingSenderId: '775850665665',
    projectId: 'ralunorvegia',
    storageBucket: 'ralunorvegia.appspot.com',
    iosBundleId: 'com.example.raluNorvegia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Vrear_iITmNGdn9urWC0Zunw9X1RYys',
    appId: '1:775850665665:ios:69dc87772a4394ecf7d640',
    messagingSenderId: '775850665665',
    projectId: 'ralunorvegia',
    storageBucket: 'ralunorvegia.appspot.com',
    iosBundleId: 'com.example.raluNorvegia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWgucuXfqfClcu738fXH1zT_GpTKrdhM',
    appId: '1:775850665665:web:dfe17902e30b6cddf7d640',
    messagingSenderId: '775850665665',
    projectId: 'ralunorvegia',
    authDomain: 'ralunorvegia.firebaseapp.com',
    storageBucket: 'ralunorvegia.appspot.com',
    measurementId: 'G-SEVJDYZLTZ',
  );
}
